server:
  port: 8080

api:
  url:
    domain: "jsonplaceholder.typicode.com"
    endpoint: 
      user: "users"
      post: "posts"
      comment: "comments"

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/sb_jph"
    username: "postgres"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate.ddl-auto: create